"""Real-Time Chunking (RTC) utilities for PyTorch.

RTC improves the smoothness of action chunks generated by diffusion/flow-matching
policies by guiding the denoising process towards the previous chunk's predictions.
"""

import math
from dataclasses import dataclass

import torch


@dataclass
class RTCConfig:
    """Configuration for Real-Time Chunking guidance."""

    # Whether RTC is enabled
    enabled: bool = False
    # Attention schedule for prefix weights: "zeros" | "ones" | "linear" | "exp"
    prefix_attention_schedule: str = "linear"
    # Max guidance weight (if None, defaults to num_steps)
    max_guidance_weight: float | None = None
    # Execution horizon for building prefix weights
    execution_horizon: int = 10
    # Prior variance scale parameter
    sigma_d: float = 1.0


def get_prefix_weights(
    start: int,
    end: int,
    total: int,
    schedule: str = "linear",
) -> torch.Tensor:
    """Compute prefix attention weights for RTC guidance.

    Generates a weight vector of shape (total,):
        [1.0, ..., 1.0, ramp↓, 0.0, ..., 0.0]
         ←── start ──→ ←end-start→ ←total-end→

    Args:
        start: Number of frozen prefix steps (inference delay).
        end: Execution horizon (end of ramp region).
        total: Total action horizon.
        schedule: Weight decay schedule ("zeros", "ones", "linear", "exp").

    Returns:
        Tensor of shape (total,) with values in [0, 1].
    """
    # Clamp to valid ranges
    start = min(max(start, 0), total)
    end = min(max(end, 0), total)
    start = min(start, end)

    weights = torch.zeros(total, dtype=torch.float32)

    if schedule == "zeros":
        # Only frozen prefix gets weight 1
        if start > 0:
            weights[:start] = 1.0

    elif schedule == "ones":
        # Everything up to end gets weight 1
        if end > 0:
            weights[:end] = 1.0

    elif schedule == "linear":
        # Frozen prefix: weight 1
        if start > 0:
            weights[:start] = 1.0
        # Ramp region: linear decay from ~1 to ~0
        ramp_len = end - start
        if ramp_len > 0:
            # Matches LeRobot convention: linspace(1, 0, steps+2)[1:-1]
            ramp_vals = torch.linspace(1.0, 0.0, ramp_len + 2)[1:-1]
            weights[start:end] = ramp_vals

    elif schedule == "exp":
        # Start from linear, then apply exponential transform to accelerate decay
        if start > 0:
            weights[:start] = 1.0
        ramp_len = end - start
        if ramp_len > 0:
            ramp_vals = torch.linspace(1.0, 0.0, ramp_len + 2)[1:-1]
            weights[start:end] = ramp_vals
        # Exponential transform: maps [0,1] -> [0,1] with faster decay
        weights = (torch.exp(weights) - 1.0) / (math.e - 1.0)

    else:
        raise ValueError(f"Unknown RTC schedule: {schedule!r}")

    return weights
