#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Piper Robot Arm State Visualization Tool (Enhanced)

Reads log files generated by inference_smooth_0912.py:
- action_sent_*.csv: 6 joint commands + gripper
- end_pose_*.csv: X, Y, Z, RX, RY, RZ (7 columns)
- joint_state_*.csv: J1-J6 feedback (7 columns)
- joint_vel_*.csv: J1-J6 velocities (7 columns)

Usage:
    python piper_state_visualizer.py --log_dir /path/to/logs --timestamp 20260112_100000
    python piper_state_visualizer.py --action_csv ... --pose_csv ... --joint_csv ... --vel_csv ...
"""

import argparse
import os
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
from typing import Optional


# ==================== 美化配置 ====================
# 使用现代配色方案
COLORS_POSITION = ['#E74C3C', '#27AE60', '#3498DB']  # 红、绿、蓝 - 位置
COLORS_ROTATION = ['#9B59B6', '#E67E22', '#1ABC9C']  # 紫、橙、青 - 姿态
COLORS_JOINTS = ['#E74C3C', '#E67E22', '#F1C40F', '#27AE60', '#3498DB', '#9B59B6']  # J1-J6
COLORS_VEL_ACC = ['#3498DB', '#E74C3C']  # 蓝=线性量, 红=角度量

# 设置全局样式
plt.rcParams.update({
    'figure.facecolor': '#FAFAFA',
    'axes.facecolor': '#FFFFFF',
    'axes.edgecolor': '#CCCCCC',
    'axes.labelcolor': '#333333',
    'axes.titleweight': 'bold',
    'xtick.color': '#666666',
    'ytick.color': '#666666',
    'grid.color': '#E0E0E0',
    'grid.linestyle': '--',
    'grid.alpha': 0.7,
    'font.size': 10,
    'axes.titlesize': 12,
    'axes.labelsize': 10,
    'legend.fontsize': 9,
    'legend.framealpha': 0.9,
    'lines.linewidth': 1.5,
    'lines.antialiased': True,
})


def find_latest_logs(log_dir: str, timestamp: Optional[str] = None):
    """Find log files in the specified directory"""
    if timestamp:
        action_csv = os.path.join(log_dir, f"action_sent_{timestamp}.csv")
        pose_csv = os.path.join(log_dir, f"end_pose_{timestamp}.csv")
        joint_csv = os.path.join(log_dir, f"joint_state_{timestamp}.csv")
        vel_csv = os.path.join(log_dir, f"joint_vel_{timestamp}.csv")
    else:
        # Find the latest log files
        action_files = sorted(glob.glob(os.path.join(log_dir, "action_sent_*.csv")))
        pose_files = sorted(glob.glob(os.path.join(log_dir, "end_pose_*.csv")))
        joint_files = sorted(glob.glob(os.path.join(log_dir, "joint_state_*.csv")))
        vel_files = sorted(glob.glob(os.path.join(log_dir, "joint_vel_*.csv")))
        
        action_csv = action_files[-1] if action_files else None
        pose_csv = pose_files[-1] if pose_files else None
        joint_csv = joint_files[-1] if joint_files else None
        vel_csv = vel_files[-1] if vel_files else None
    
    return action_csv, pose_csv, joint_csv, vel_csv


def load_csv(path: str, header=None):
    """加载 CSV 文件"""
    if path and os.path.exists(path):
        return pd.read_csv(path, header=header)
    return None


def plot_visualization(action_csv: str, pose_csv: str, joint_csv: str, vel_csv: str, output: str):
    """Generate visualization with 5 subplots"""
    
    # Load data
    action_df = load_csv(action_csv)
    pose_df = load_csv(pose_csv)
    joint_df = load_csv(joint_csv)
    vel_df = load_csv(vel_csv)
    
    # 创建图形布局: 5行1列
    fig = plt.figure(figsize=(16, 20))
    fig.patch.set_facecolor('#FAFAFA')
    
    # 使用 GridSpec 进行更灵活的布局
    gs = GridSpec(5, 1, figure=fig, height_ratios=[1, 1, 1, 1, 1], hspace=0.35)
    
    # ==================== Figure 1: Sent Joint Actions (J1-J6) ====================
    ax1 = fig.add_subplot(gs[0, 0])
    if action_df is not None and action_df.shape[1] >= 7:
        t = action_df.iloc[:, 0] - action_df.iloc[0, 0]  # relative time
        joint_data = [action_df.iloc[:, i+1] for i in range(6)]
        labels = [f'J{i+1} cmd' for i in range(6)]
        
        for i, (d, c, l) in enumerate(zip(joint_data, COLORS_JOINTS, labels)):
            ax1.plot(t, d, color=c, label=l, alpha=0.85, linewidth=1.5)
        
        ax1.set_title("📤 Sent Joint Action Commands (J1-J6)", fontsize=13, pad=12, fontweight='bold')
        ax1.set_xlabel("Time (s)")
        ax1.set_ylabel("Position (Piper units)")
        ax1.legend(loc='upper right', ncol=3, frameon=True, fancybox=True, shadow=True)
        ax1.grid(True, alpha=0.5)
    else:
        ax1.set_title("📤 Sent Joint Action Commands (No Data)", fontsize=13)
        ax1.text(0.5, 0.5, 'No Data', ha='center', va='center', fontsize=14, color='gray')
    
    # ==================== Figure 2: Joint Feedback States (J1-J6) ====================
    ax2 = fig.add_subplot(gs[1, 0])
    if joint_df is not None and joint_df.shape[1] >= 7:
        t = joint_df.iloc[:, 0] - joint_df.iloc[0, 0]
        joint_data = [joint_df.iloc[:, i+1] for i in range(6)]
        labels = [f'J{i+1} feedback' for i in range(6)]
        
        for i, (d, c, l) in enumerate(zip(joint_data, COLORS_JOINTS, labels)):
            ax2.plot(t, d, color=c, label=l, alpha=0.85, linewidth=1.5)
        
        ax2.set_title("📥 Joint Angle Feedback (J1-J6)", fontsize=13, pad=12, fontweight='bold')
        ax2.set_xlabel("Time (s)")
        ax2.set_ylabel("Angle (deg)")
        ax2.legend(loc='upper right', ncol=3, frameon=True, fancybox=True, shadow=True)
        ax2.grid(True, alpha=0.5)
    else:
        ax2.set_title("📥 Joint Angle Feedback (No Data)", fontsize=13)
        ax2.text(0.5, 0.5, 'No Data', ha='center', va='center', fontsize=14, color='gray')
    
    # ==================== Figure 3: End-Effector Pose (XYZ + RxRyRz Dual Axis) ====================
    ax3 = fig.add_subplot(gs[2, 0])
    if pose_df is not None and pose_df.shape[1] >= 7:
        t = pose_df.iloc[:, 0] - pose_df.iloc[0, 0]
        
        # Left Y-axis: Position XYZ
        pos_data = [pose_df.iloc[:, i+1] for i in range(3)]
        pos_labels = ['X (mm)', 'Y (mm)', 'Z (mm)']
        
        for d, c, l in zip(pos_data, COLORS_POSITION, pos_labels):
            ax3.plot(t, d, color=c, label=l, alpha=0.85, linewidth=1.8)
        
        ax3.set_ylabel("Position (mm)", color='#333333')
        ax3.tick_params(axis='y', labelcolor='#333333')
        
        # Right Y-axis: Orientation RxRyRz
        ax3_twin = ax3.twinx()
        rot_data = [pose_df.iloc[:, i+4] for i in range(3)]
        rot_labels = ['RX (deg)', 'RY (deg)', 'RZ (deg)']
        
        for d, c, l in zip(rot_data, COLORS_ROTATION, rot_labels):
            ax3_twin.plot(t, d, color=c, label=l, alpha=0.85, linewidth=1.8, linestyle='--')
        
        ax3_twin.set_ylabel("Orientation (deg)", color='#666666')
        ax3_twin.tick_params(axis='y', labelcolor='#666666')
        
        # Merge legends
        lines1, labels1 = ax3.get_legend_handles_labels()
        lines2, labels2 = ax3_twin.get_legend_handles_labels()
        ax3.legend(lines1 + lines2, labels1 + labels2, loc='upper right', ncol=3,
                   frameon=True, fancybox=True, shadow=True)
        
        ax3.set_title("🎯 End-Effector Pose (Position + Orientation)", fontsize=13, pad=12, fontweight='bold')
        ax3.set_xlabel("Time (s)")
        ax3.grid(True, alpha=0.5)
    else:
        ax3.set_title("🎯 End-Effector Pose (No Data)", fontsize=13)
        ax3.text(0.5, 0.5, 'No Data', ha='center', va='center', fontsize=14, color='gray')
    
    # ==================== Figure 4: Joint Velocities (J1-J6) from joint_vel_*.csv ====================
    ax4 = fig.add_subplot(gs[3, 0])
    if vel_df is not None and vel_df.shape[1] >= 7:
        t = vel_df.iloc[:, 0] - vel_df.iloc[0, 0]
        
        # Plot all 6 joint velocities
        joint_vel_data = [vel_df.iloc[:, i+1] for i in range(6)]
        labels = [f'J{i+1} vel' for i in range(6)]
        
        for d, c, l in zip(joint_vel_data, COLORS_JOINTS, labels):
            ax4.plot(t, d, color=c, label=l, alpha=0.85, linewidth=1.5)
        
        ax4.set_title("Joint Velocities (J1-J6)", fontsize=13, pad=12, fontweight='bold')
        ax4.set_xlabel("Time (s)")
        ax4.set_ylabel("Velocity (rad/s)")
        ax4.legend(loc='upper right', ncol=3, frameon=True, fancybox=True, shadow=True)
        ax4.grid(True, alpha=0.5)
    else:
        ax4.set_title("Joint Velocities (No Data)", fontsize=13)
        ax4.text(0.5, 0.5, 'No Data (Requires joint_vel_*.csv)', ha='center', va='center', fontsize=14, color='gray')
    
    # ==================== Figure 5: Data Summary ====================
    ax5 = fig.add_subplot(gs[4, 0])
    ax5.set_title("Data Summary", fontsize=13, pad=12, fontweight='bold')
    summary_text = []
    if action_df is not None:
        summary_text.append(f"Action samples: {len(action_df)}")
    if pose_df is not None:
        summary_text.append(f"Pose samples: {len(pose_df)}")
        if len(pose_df) > 0:
            duration = pose_df.iloc[-1, 0] - pose_df.iloc[0, 0]
            summary_text.append(f"Duration: {duration:.2f}s")
    if joint_df is not None:
        summary_text.append(f"Joint samples: {len(joint_df)}")
    if vel_df is not None:
        summary_text.append(f"Velocity samples: {len(vel_df)}")
    if summary_text:
        ax5.text(0.5, 0.5, '\n'.join(summary_text), ha='center', va='center', fontsize=12,
                 fontfamily='monospace', bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
    else:
        ax5.text(0.5, 0.5, 'No Data Summary Available', ha='center', va='center', fontsize=14, color='gray')
    ax5.axis('off')
    
    # Main Title
    fig.suptitle("🤖 Piper Robot State Visualization Dashboard", 
                 fontsize=16, fontweight='bold', y=0.995, color='#2C3E50')
    
    # 调整布局
    plt.tight_layout(rect=[0, 0, 1, 0.98])
    
    if output:
        plt.savefig(output, dpi=150, bbox_inches='tight', facecolor='#FAFAFA')
        print(f"[OK] 图表已保存到 {output}")
    else:
        plt.show()


def main():
    parser = argparse.ArgumentParser(
        description="Piper Robot Arm State Visualization (Enhanced)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Read latest logs from directory
  python piper_state_visualizer.py --log_dir /home/test/test_tra
  
  # Specify timestamp
  python piper_state_visualizer.py --log_dir /home/test/test_tra --timestamp 20260112_100000
  
  # Specify individual CSV files
  python piper_state_visualizer.py --action_csv action.csv --pose_csv pose.csv --joint_csv joint.csv --vel_csv vel.csv
  
  # Save as image
  python piper_state_visualizer.py --log_dir /home/test/test_tra --output result.png

Log format:
  - action_sent_*.csv: timestamp, J1-J6, gripper (8 columns)
  - end_pose_*.csv: timestamp, X, Y, Z, RX, RY, RZ (7 columns)
  - joint_state_*.csv: timestamp, J1-J6 (7 columns)
  - joint_vel_*.csv: timestamp, J1_vel...J6_vel (7 columns)
        """
    )
    parser.add_argument("--log_dir", type=str, help="Log directory path")
    parser.add_argument("--timestamp", type=str, help="Log timestamp (e.g. 20260112_100000)")
    parser.add_argument("--action_csv", type=str, help="Path to action_sent CSV file")
    parser.add_argument("--pose_csv", type=str, help="Path to end_pose CSV file")
    parser.add_argument("--joint_csv", type=str, help="Path to joint_state CSV file")
    parser.add_argument("--vel_csv", type=str, help="Path to joint_vel CSV file")
    parser.add_argument("--output", type=str, default="", help="Output image path (leave empty to show window)")
    args = parser.parse_args()
    
    # Determine CSV file paths
    if args.log_dir:
        action_csv, pose_csv, joint_csv, vel_csv = find_latest_logs(args.log_dir, args.timestamp)
    else:
        action_csv = args.action_csv
        pose_csv = args.pose_csv
        joint_csv = args.joint_csv
        vel_csv = args.vel_csv
    
    print("=" * 60)
    print("Piper Robot Arm State Visualizer")
    print("=" * 60)
    print(f"  Action CSV   : {action_csv}")
    print(f"  Pose CSV     : {pose_csv}")
    print(f"  Joint CSV    : {joint_csv}")
    print(f"  Velocity CSV : {vel_csv}")
    print("=" * 60)
    
    if not any([action_csv, pose_csv, joint_csv, vel_csv]):
        print("[ERR] No log files found")
        return
    
    # Generate visualization
    plot_visualization(action_csv, pose_csv, joint_csv, vel_csv, args.output)


if __name__ == "__main__":
    main()
