#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Piper Robot Arm State Visualization Tool (Enhanced)

Reads log files generated by inference_smooth_0912.py:
- action_sent_*.csv: 6 joint commands + gripper (raw pulses)
- end_pose_*.csv: X, Y, Z, RX, RY, RZ
- joint_state_*.csv: J1-J6 feedback (degrees)
- joint_vel_*.csv: J1-J6 velocities (rad/s)
- merge_events_*.csv: timestamp when new action chunk is merged

Features:
- Action chunk boundary markers (1.67s dashed lines)
- **Merge Event Markers (Red V-lines)**: Indicates when new inference result was merged
- Unified Units (SI): All angular data converted to Radians
- Calculated velocity/acceleration/jerk from sent actions (rad/s, rad/s², rad/s³)
- Comparison with actual feedback velocities (rad/s)

Usage:
    python piper_state_visualizer.py --log_dir /path/to/logs --timestamp 20260112_100000
"""

import argparse
import os
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
from typing import Optional, Tuple

# ==================== Configuration ====================
# Action chunk period: 50 actions / 30Hz = 1.67s
ACTION_CHUNK_PERIOD = 50 / 30.0  # 1.67 seconds

# Unit Conversions
PULSE_TO_DEG = 0.001        # 1 Pulse = 0.001 Degree
DEG_TO_RAD = np.pi / 180.0  # 1 Degree = pi/180 Radians
PULSE_TO_RAD = PULSE_TO_DEG * DEG_TO_RAD  # 1 Pulse = ~1.745e-5 Radians

# Color schemes
COLORS_POSITION = ['#E74C3C', '#27AE60', '#3498DB']  # Red, Green, Blue - Position
COLORS_ROTATION = ['#9B59B6', '#E67E22', '#1ABC9C']  # Purple, Orange, Cyan - Orientation
COLORS_JOINTS = ['#E74C3C', '#E67E22', '#F1C40F', '#27AE60', '#3498DB', '#9B59B6']  # J1-J6

# Global style
plt.rcParams.update({
    'figure.facecolor': '#FAFAFA',
    'axes.facecolor': '#FFFFFF',
    'axes.edgecolor': '#CCCCCC',
    'axes.labelcolor': '#333333',
    'axes.titleweight': 'bold',
    'xtick.color': '#666666',
    'ytick.color': '#666666',
    'grid.color': '#E0E0E0',
    'grid.linestyle': '--',
    'grid.alpha': 0.7,
    'font.size': 10,
    'axes.titlesize': 12,
    'axes.labelsize': 10,
    'legend.fontsize': 9,
    'legend.framealpha': 0.9,
    'lines.linewidth': 1.5,
    'lines.antialiased': True,
})


def compute_derivatives(positions: np.ndarray, times: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Compute velocity, acceleration, and jerk from position sequence.
    
    Args:
        positions: (N, D) position array (assumed in Radians)
        times: (N,) time array
    
    Returns:
        vel_times, velocity (rad/s), acc_times, acceleration (rad/s^2), jerk_times, jerk (rad/s^3)
    """
    if len(positions) < 2:
        zeros = np.zeros_like(positions)
        return times, zeros, times, zeros, times, zeros
    
    # Time differences
    dt = np.diff(times)
    dt[dt == 0] = 1e-6  # Avoid division by zero
    
    # Velocity = first derivative
    velocity = np.diff(positions, axis=0) / dt[:, np.newaxis]
    vel_times = times[:-1] + dt / 2
    
    # Acceleration = second derivative
    if len(velocity) > 1:
        dt_v = np.diff(vel_times)
        dt_v[dt_v == 0] = 1e-6
        acceleration = np.diff(velocity, axis=0) / dt_v[:, np.newaxis]
        acc_times = vel_times[:-1] + dt_v / 2
    else:
        acceleration = np.zeros_like(velocity)
        acc_times = vel_times
    
    # Jerk = third derivative
    if len(acceleration) > 1:
        dt_a = np.diff(acc_times)
        dt_a[dt_a == 0] = 1e-6
        jerk = np.diff(acceleration, axis=0) / dt_a[:, np.newaxis]
        jerk_times = acc_times[:-1] + dt_a / 2
    else:
        jerk = np.zeros_like(acceleration)
        jerk_times = acc_times
    
    return vel_times, velocity, acc_times, acceleration, jerk_times, jerk


def add_chunk_markers(ax, max_time: float, period: float = ACTION_CHUNK_PERIOD):
    """Add vertical lines at action chunk boundaries."""
    t = period
    while t < max_time:
        ax.axvline(x=t, color='#AAAAAA', linestyle=':', linewidth=1.0, alpha=0.6)
        t += period


def find_latest_logs(log_dir: str, timestamp: Optional[str] = None):
    """Find log files in the specified directory."""
    if timestamp:
        action_csv = os.path.join(log_dir, f"action_sent_{timestamp}.csv")
        pose_csv = os.path.join(log_dir, f"end_pose_{timestamp}.csv")
        joint_csv = os.path.join(log_dir, f"joint_state_{timestamp}.csv")
        vel_csv = os.path.join(log_dir, f"joint_vel_{timestamp}.csv")
        merge_csv = os.path.join(log_dir, f"merge_events_{timestamp}.csv")
        if not os.path.exists(merge_csv): merge_csv = None
    else:
        action_files = sorted(glob.glob(os.path.join(log_dir, "action_sent_*.csv")))
        pose_files = sorted(glob.glob(os.path.join(log_dir, "end_pose_*.csv")))
        joint_files = sorted(glob.glob(os.path.join(log_dir, "joint_state_*.csv")))
        vel_files = sorted(glob.glob(os.path.join(log_dir, "joint_vel_*.csv")))
        merge_files = sorted(glob.glob(os.path.join(log_dir, "merge_events_*.csv")))
        
        action_csv = action_files[-1] if action_files else None
        pose_csv = pose_files[-1] if pose_files else None
        joint_csv = joint_files[-1] if joint_files else None
        vel_csv = vel_files[-1] if vel_files else None
        merge_csv = merge_files[-1] if merge_files else None
    
    return action_csv, pose_csv, joint_csv, vel_csv, merge_csv


def load_csv(path: str, header=None):
    """Load CSV file."""
    if path and os.path.exists(path):
        return pd.read_csv(path, header=header)
    return None


def plot_visualization(action_csv: str, pose_csv: str, joint_csv: str, vel_csv: str, merge_csv: str, output: str):
    """Generate visualization with 8 subplots with Unified SI Units (Radians)."""
    
    # Load data
    action_df = load_csv(action_csv)
    pose_df = load_csv(pose_csv)
    joint_df = load_csv(joint_csv)
    vel_df = load_csv(vel_csv)
    merge_df = load_csv(merge_csv)

    # Determine global start time (t0)
    t0 = np.inf
    if action_df is not None: t0 = min(t0, action_df.iloc[0, 0])
    if pose_df is not None: t0 = min(t0, pose_df.iloc[0, 0])
    if joint_df is not None: t0 = min(t0, joint_df.iloc[0, 0])
    if vel_df is not None: t0 = min(t0, vel_df.iloc[0, 0])
    if t0 == np.inf: t0 = 0.0

    # Func to add merge markers
    def add_merge_markers(ax, merge_df, t0):
        if merge_df is not None:
            merge_times = merge_df.iloc[:, 0] - t0
            for mt in merge_times:
                ax.axvline(x=mt, color='#FF4500', linestyle='-', linewidth=0.8, alpha=0.5)
            # Add legend entry only once (using a proxy artist if needed, but here simple hack)
            # ax.plot([], [], color='#FF4500', linestyle='-', linewidth=0.8, label='Merge Event')

    # Calculate derivatives from action commands (Convert Pulse -> Radian first)
    calc_vel, calc_acc, calc_jerk = None, None, None
    calc_vel_times, calc_acc_times, calc_jerk_times = None, None, None
    action_rad = None
    
    if action_df is not None and action_df.shape[1] >= 7:
        times = (action_df.iloc[:, 0] - t0).values # Use t0
        # CONVERT: Pulse -> Radians
        action_pulse = action_df.iloc[:, 1:7].values
        action_rad = action_pulse * PULSE_TO_RAD
        
        calc_vel_times, calc_vel, calc_acc_times, calc_acc, calc_jerk_times, calc_jerk = compute_derivatives(action_rad, times)
    
    # Get max time for chunk markers
    max_time = 0
    if action_df is not None:
        max_time = max(max_time, action_df.iloc[-1, 0] - t0)
    if pose_df is not None:
        max_time = max(max_time, pose_df.iloc[-1, 0] - t0)
    
    # Create figure: 8 rows
    fig = plt.figure(figsize=(18, 32))
    fig.patch.set_facecolor('#FAFAFA')
    gs = GridSpec(8, 1, figure=fig, height_ratios=[1, 1, 1, 1, 1, 1, 1, 0.6], hspace=0.35)
    
    # ==================== Figure 1: Sent Joint Actions (Radians) ====================
    ax1 = fig.add_subplot(gs[0, 0])
    if action_rad is not None:
        t = times
        for i in range(6):
            ax1.plot(t, action_rad[:, i], color=COLORS_JOINTS[i], 
                    label=f'J{i+1} cmd', alpha=0.85, linewidth=1.5)
        
        add_chunk_markers(ax1, max_time)
        add_merge_markers(ax1, merge_df, t0)
        ax1.set_title("Sent Joint Action Commands (Converted to Radians) | Red solid lines = New Inference Merge", 
                     fontsize=13, pad=12, fontweight='bold')
        ax1.set_xlabel("Time (s)")
        ax1.set_ylabel("Position (rad)")
        ax1.legend(loc='upper right', ncol=3, frameon=True, fancybox=True, shadow=True)
        ax1.grid(True, alpha=0.5)
    else:
        ax1.set_title("Sent Joint Actions (No Data)", fontsize=13)
        ax1.text(0.5, 0.5, 'No Data', ha='center', va='center', fontsize=14, color='gray')

    # ==================== Figure 2: Actual Joint Feedback Positions (Radians) ====================
    ax2 = fig.add_subplot(gs[1, 0])
    if joint_df is not None and joint_df.shape[1] >= 7:
        t = joint_df.iloc[:, 0] - joint_df.iloc[0, 0]
        # CONVERT: Degrees -> Radians (assuming log is raw/1000 degrees?)
        # NOTE: inference_smooth_0912.py logs js.joint_1 / 1000.0. 
        # If Piper returns Pulses, then /1000 is Degrees. If Piper returns Degrees*1000, then /1000 is Degrees.
        # AgileXFollower comments imply 0.001 deg/pulse.
        # Let's assume the log file (joint_state_*.csv) contains Degrees.
        fb_pos_rad = joint_df.iloc[:, 1:7].values * DEG_TO_RAD
        
        for i in range(6):
            ax2.plot(t, fb_pos_rad[:, i], color=COLORS_JOINTS[i], 
                    label=f'J{i+1} fbk', alpha=0.85, linewidth=1.5, linestyle='-')
        
        add_chunk_markers(ax2, max_time)
        add_merge_markers(ax2, merge_df, t0)
        ax2.set_title("Actual Joint Feedback Positions (Converted to Radians)", 
                     fontsize=13, pad=12, fontweight='bold')
        ax2.set_xlabel("Time (s)")
        ax2.set_ylabel("Position (rad)")
        ax2.legend(loc='upper right', ncol=3, frameon=True, fancybox=True, shadow=True)
        ax2.grid(True, alpha=0.5)
    else:
        ax2.set_title("Actual Joint Feedback Positions (No Data)", fontsize=13)
        ax2.text(0.5, 0.5, 'No Data', ha='center', va='center', fontsize=14, color='gray')
    
    # ==================== Figure 3: Calculated Velocity from Actions (Rad/s) ====================
    ax3 = fig.add_subplot(gs[2, 0])
    if calc_vel is not None and len(calc_vel) > 0:
        for i in range(6):
            ax3.plot(calc_vel_times, calc_vel[:, i], color=COLORS_JOINTS[i], 
                    label=f'J{i+1} calc vel', alpha=0.85, linewidth=1.2)
        
        add_chunk_markers(ax3, max_time)
        add_merge_markers(ax3, merge_df, t0)
        ax3.set_title("Calculated Velocity from Sent Actions (d(rad)/dt)", 
                     fontsize=13, pad=12, fontweight='bold')
        ax3.set_xlabel("Time (s)")
        ax3.set_ylabel("Velocity (rad/s)")
        ax3.legend(loc='upper right', ncol=3, frameon=True, fancybox=True, shadow=True)
        ax3.grid(True, alpha=0.5)
    else:
        ax3.set_title("Calculated Velocity (No Data)", fontsize=13)
        ax3.text(0.5, 0.5, 'No Data', ha='center', va='center', fontsize=14, color='gray')
    
    # ==================== Figure 4: Calculated Acceleration from Actions (Rad/s^2) ====================
    ax4 = fig.add_subplot(gs[3, 0])
    if calc_acc is not None and len(calc_acc) > 0:
        for i in range(6):
            ax4.plot(calc_acc_times, calc_acc[:, i], color=COLORS_JOINTS[i], 
                    label=f'J{i+1} acc', alpha=0.85, linewidth=1.2)
        
        add_chunk_markers(ax4, max_time)
        add_merge_markers(ax4, merge_df, t0)
        ax4.set_title("Calculated Acceleration from Sent Actions (d²(rad)/dt²)", 
                     fontsize=13, pad=12, fontweight='bold')
        ax4.set_xlabel("Time (s)")
        ax4.set_ylabel("Acceleration (rad/s²)")
        ax4.legend(loc='upper right', ncol=3, frameon=True, fancybox=True, shadow=True)
        ax4.grid(True, alpha=0.5)
    else:
        ax4.set_title("Calculated Acceleration (No Data)", fontsize=13)
        ax4.text(0.5, 0.5, 'No Data', ha='center', va='center', fontsize=14, color='gray')
    
    # ==================== Figure 5: Calculated Jerk from Actions (Rad/s^3) ====================
    ax5 = fig.add_subplot(gs[4, 0])
    if calc_jerk is not None and len(calc_jerk) > 0:
        for i in range(6):
            ax5.plot(calc_jerk_times, calc_jerk[:, i], color=COLORS_JOINTS[i], 
                    label=f'J{i+1} jerk', alpha=0.85, linewidth=1.2)
        
        add_chunk_markers(ax5, max_time)
        add_merge_markers(ax5, merge_df, t0)
        ax5.set_title("Calculated Jerk from Sent Actions (d³(rad)/dt³)", 
                     fontsize=13, pad=12, fontweight='bold')
        ax5.set_xlabel("Time (s)")
        ax5.set_ylabel("Jerk (rad/s³)")
        ax5.legend(loc='upper right', ncol=3, frameon=True, fancybox=True, shadow=True)
        ax5.grid(True, alpha=0.5)
    else:
        ax5.set_title("Calculated Jerk (No Data)", fontsize=13)
        ax5.text(0.5, 0.5, 'No Data', ha='center', va='center', fontsize=14, color='gray')
    
    # ==================== Figure 6: Actual Feedback Velocity (Rad/s) ====================
    ax6 = fig.add_subplot(gs[5, 0])
    if vel_df is not None and vel_df.shape[1] >= 7:
        t = vel_df.iloc[:, 0] - vel_df.iloc[0, 0]
        for i in range(6):
            ax6.plot(t, vel_df.iloc[:, i+1], color=COLORS_JOINTS[i], 
                    label=f'J{i+1} feedback vel', alpha=0.85, linewidth=1.5)
        
        add_chunk_markers(ax6, max_time)
        add_merge_markers(ax6, merge_df, t0)
        ax6.set_title("Actual Joint Velocity Feedback (SI Unit: rad/s)", 
                     fontsize=13, pad=12, fontweight='bold')
        ax6.set_xlabel("Time (s)")
        ax6.set_ylabel("Velocity (rad/s)")
        ax6.legend(loc='upper right', ncol=3, frameon=True, fancybox=True, shadow=True)
        ax6.grid(True, alpha=0.5)
    else:
        ax6.set_title("Actual Joint Velocity Feedback (No Data)", fontsize=13)
        ax6.text(0.5, 0.5, 'No Data', ha='center', va='center', fontsize=14, color='gray')
    
    # ==================== Figure 7: End-Effector Pose ====================
    ax7 = fig.add_subplot(gs[6, 0])
    if pose_df is not None and pose_df.shape[1] >= 7:
        t = pose_df.iloc[:, 0] - t0 # Use t0
        
        # Position XYZ
        for i, (c, l) in enumerate(zip(COLORS_POSITION, ['X', 'Y', 'Z'])):
            ax7.plot(t, pose_df.iloc[:, i+1], color=c, label=f'{l} (mm)', alpha=0.85, linewidth=1.8)
        
        ax7.set_ylabel("Position (mm)", color='#333333')
        
        # Orientation RxRyRz on twin axis
        ax7_twin = ax7.twinx()
        for i, (c, l) in enumerate(zip(COLORS_ROTATION, ['RX', 'RY', 'RZ'])):
            ax7_twin.plot(t, pose_df.iloc[:, i+4], color=c, label=f'{l} (deg)', 
                         alpha=0.85, linewidth=1.8, linestyle='--')
        
        ax7_twin.set_ylabel("Orientation (deg)", color='#666666')
        
        add_chunk_markers(ax7, max_time)
        add_merge_markers(ax7, merge_df, t0)
        
        # Merge legends
        lines1, labels1 = ax7.get_legend_handles_labels()
        lines2, labels2 = ax7_twin.get_legend_handles_labels()
        ax7.legend(lines1 + lines2, labels1 + labels2, loc='upper right', ncol=3,
                   frameon=True, fancybox=True, shadow=True)
        
        ax7.set_title("End-Effector Pose (Position + Orientation)", fontsize=13, pad=12, fontweight='bold')
        ax7.set_xlabel("Time (s)")
        ax7.grid(True, alpha=0.5)
    else:
        ax7.set_title("End-Effector Pose (No Data)", fontsize=13)
        ax7.text(0.5, 0.5, 'No Data', ha='center', va='center', fontsize=14, color='gray')
    
    # ==================== Figure 8: Data Summary ====================
    ax8 = fig.add_subplot(gs[7, 0])
    ax8.set_title("Data Summary", fontsize=13, pad=12, fontweight='bold')
    summary_lines = []
    
    if action_df is not None:
        summary_lines.append(f"Action samples: {len(action_df)}")
        duration = action_df.iloc[-1, 0] - action_df.iloc[0, 0]
        summary_lines.append(f"Duration: {duration:.2f}s")
        summary_lines.append(f"Action chunks (~1.67s): {int(duration / ACTION_CHUNK_PERIOD) + 1}")
    if pose_df is not None:
        summary_lines.append(f"Pose samples: {len(pose_df)}")
    if joint_df is not None:
        summary_lines.append(f"Joint samples: {len(joint_df)}")
    if vel_df is not None:
        summary_lines.append(f"Velocity samples: {len(vel_df)}")
    
    # Add velocity comparison stats if both available
    if calc_vel is not None and vel_df is not None:
        summary_lines.append("---")
        summary_lines.append(f"Calc vel range: [{np.min(calc_vel):.1f}, {np.max(calc_vel):.1f}]")
        summary_lines.append(f"Feedback vel range: [{vel_df.iloc[:, 1:7].min().min():.3f}, {vel_df.iloc[:, 1:7].max().max():.3f}]")
    
    if summary_lines:
        ax8.text(0.5, 0.5, '\n'.join(summary_lines), ha='center', va='center', fontsize=11,
                 fontfamily='monospace', bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
    else:
        ax8.text(0.5, 0.5, 'No Data', ha='center', va='center', fontsize=14, color='gray')
    ax8.axis('off')
    
    # Main Title
    fig.suptitle("Piper Robot State Visualization Dashboard (with Derivatives Analysis)", 
                 fontsize=16, fontweight='bold', y=0.995, color='#2C3E50')
    
    plt.tight_layout(rect=[0, 0, 1, 0.98])
    
    if output:
        plt.savefig(output, dpi=150, bbox_inches='tight', facecolor='#FAFAFA')
        print(f"[OK] Chart saved to {output}")
    else:
        plt.show()


def main():
    parser = argparse.ArgumentParser(
        description="Piper Robot Arm State Visualization (Enhanced with Derivatives)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python piper_state_visualizer.py --log_dir /home/test/logs
  python piper_state_visualizer.py --log_dir /home/test/logs --timestamp 20260112_100000
  python piper_state_visualizer.py --log_dir /home/test/logs --output result.png

Log format:
  - action_sent_*.csv: timestamp, J1-J6, gripper (8 columns)
  - end_pose_*.csv: timestamp, X, Y, Z, RX, RY, RZ (7 columns)
  - joint_state_*.csv: timestamp, J1-J6 (7 columns)
  - joint_vel_*.csv: timestamp, J1_vel...J6_vel (7 columns)
        """
    )
    parser.add_argument("--log_dir", type=str, help="Log directory path")
    parser.add_argument("--timestamp", type=str, help="Log timestamp (e.g. 20260112_100000)")
    parser.add_argument("--action_csv", type=str, help="Path to action_sent CSV file")
    parser.add_argument("--pose_csv", type=str, help="Path to end_pose CSV file")
    parser.add_argument("--joint_csv", type=str, help="Path to joint_state CSV file")
    parser.add_argument("--vel_csv", type=str, help="Path to joint_vel CSV file")
    parser.add_argument("--merge_csv", type=str, help="Path to merge_events CSV file")
    parser.add_argument("--output", type=str, default="", help="Output image path (leave empty to show window)")
    args = parser.parse_args()
    
    if args.log_dir:
        action_csv, pose_csv, joint_csv, vel_csv, merge_csv = find_latest_logs(args.log_dir, args.timestamp)
    else:
        action_csv = args.action_csv
        pose_csv = args.pose_csv
        joint_csv = args.joint_csv
        vel_csv = args.vel_csv
        merge_csv = args.merge_csv
    
    print("=" * 60)
    print("Piper Robot Arm State Visualizer (Enhanced)")
    print("=" * 60)
    print(f"  Action CSV   : {action_csv}")
    print(f"  Pose CSV     : {pose_csv}")
    print(f"  Joint CSV    : {joint_csv}")
    print(f"  Velocity CSV : {vel_csv}")
    print(f"  Merge CSV    : {merge_csv}")
    print(f"  Chunk period : {ACTION_CHUNK_PERIOD:.2f}s (50 actions / 30Hz)")
    print("=" * 60)
    
    if not any([action_csv, pose_csv, joint_csv, vel_csv]):
        print("[ERR] No log files found")
        return
    
    plot_visualization(action_csv, pose_csv, joint_csv, vel_csv, merge_csv, args.output)


if __name__ == "__main__":
    main()
